export const ORDERS = [
	{
		serial_no: 1,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 500,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 2,
		user: 'raju',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 1000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'tushar',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 200,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 10,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 4,
		user: 'asif',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 5,
		user: 'jark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 100,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 100,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 6,
		user: 'dark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 500,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 510,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 7,
		user: 'clark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 510,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 40,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 9,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 10,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
];