export const ORDERS = [
	{
		serial_no: 1,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 2,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
	{
		serial_no: 3,
		user: 'mark',
		products_list: [{ 1: 2 }, { 2: 3 }],
		total_cost: 2000,
		status: 'on progress',
		shipping_address: 'titumir hall, azimpur, dhaka-1205',
		payment_method: 'bkash',
		payed_amount: 1000,
		transaction_id: 111220,
		delivery_agent: 'paperly',
		parcel_id: '',
		timestamp: '',
	},
];