export const PRODUCTS_DETAILS = [
	{
		id: 0,
		sku: '123abc',
		title:
			'Lamaze Peek-A-Boo Forest, Fun Interactive Baby Book with Inspiring Rhymes and Stories',
		slug:
			'lamaze-peek-a-boo-forest-fun-interactive-baby-book-with-inspiring-rhymes-and-stories',
		price: 21.23,
		rating: 4.5,
		discount: 10,
		image: '/images/products/handBag.jpg',
		category: 'Bag',
		description: {
			header:
				'Product details of PLEXTONE G20 Magnetic Stereo Bass GamingHeadphone for Mobile and Computer',
			features: [
				'Sensitivity (1Hz): - 45',
				'Microphone Directivity: Full Point',
				'Frequency response: 50-10000 Hz',
				'Signal to noise ratio: 55dB',
				'Headset:',
				'Frequency response: 20-22000 Hz',
				'Impedance: 32ohm + 15%',
				'Microphone sensitivity (1Hz): 102dB (max 1KHz)',
				'Input power: up to 5 horses',
				'Drive unit: 10mm, neodymium magnet',
			],
			specifications: [
				'Sensitivity (1Hz): - 45',
				'Microphone Directivity: Full Point',
				'Frequency response: 50-10000 Hz',
				'Signal to noise ratio: 55dB',
				'Headset:',
				'Frequency response: 20-22000 Hz',
				'Impedance: 32ohm + 15%',
				'Microphone sensitivity (1Hz): 102dB (max 1KHz)',
				'Input power: up to 5 horses',
				'Drive unit: 10mm, neodymium magnet',
			],
		},
		questionAns: [
			{
				user: 'raju',
				q: 'eta ki red color hobe?',
				a: 'sorry. eta just ekta color e ase.',
				qtime: '2020-10-07T06:08:29.477Z',
				atime: '2020-10-07T06:08:29.477Z',
			},
			{
				user: 'raju',
				q: 'eta ki red color hobe?',
				a: 'sorry. eta just ekta color e ase.',
				qtime: '2020-10-07T06:08:29.477Z',
				atime: '2020-10-07T06:08:29.477Z',
			},
			{
				user: 'raju',
				q: 'eta ki red color hobe?',
				a: 'sorry. eta just ekta color e ase.',
				qtime: '2020-10-07T06:08:29.477Z',
				atime: '2020-10-07T06:08:29.477Z',
			},
		],
		reviews: [
			{
				user: 'raju',
				time: '2020-10-07T06:08:29.477Z',
				rating: 3,
				comment: 'onek valo product',
			},
			{
				user: 'raju',
				time: '2020-10-07T06:08:29.477Z',
				rating: 5,
				comment: 'onek valo product',
			},
			{
				user: 'raju',
				time: '2020-10-07T06:08:29.477Z',
				rating: 5,
				comment: 'onek valo product',
			},
			{
				user: 'raju',
				time: '2020-10-07T06:08:29.477Z',
				rating: 5,
				comment: 'onek valo product',
			},
		],
	},
	{
		id: 1,
		title: 'Fjallraven, Kanken Classic Backpack for Everyday',
		price: 24.99,
		rating: 4,
		discount: 10,
		image: '/images/products/bag.jpg',
		category: 'Bag',
		slug: 'fjallraven-kanken-classic-backpack-for-everyday',
		description: {
			header:
				'Product details of PLEXTONE G20 Magnetic Stereo Bass GamingHeadphone for Mobile and Computer',
			features: [
				'Sensitivity (1Hz): - 45',
				'Microphone Directivity: Full Point',
				'Frequency response: 50-10000 Hz',
				'Signal to noise ratio: 55dB',
				'Headset:',
				'Frequency response: 20-22000 Hz',
				'Impedance: 32ohm + 15%',
				'Microphone sensitivity (1Hz): 102dB (max 1KHz)',
				'Input power: up to 5 horses',
				'Drive unit: 10mm, neodymium magnet',
			],
			specifications: [
				'Sensitivity (1Hz): - 45',
				'Microphone Directivity: Full Point',
				'Frequency response: 50-10000 Hz',
				'Signal to noise ratio: 55dB',
				'Headset:',
				'Frequency response: 20-22000 Hz',
				'Impedance: 32ohm + 15%',
				'Microphone sensitivity (1Hz): 102dB (max 1KHz)',
				'Input power: up to 5 horses',
				'Drive unit: 10mm, neodymium magnet',
			],
		},
		questionAns: [],
		reviews: [
			{
				user: 'raju',
				rating: 2,
				time: '2020-10-07T06:08:29.477Z',
				comment: 'onek valo product',
			},
			{
				user: 'raju',
				rating: 2,
				time: '2020-10-07T06:08:29.477Z',
				comment: 'onek valo product',
			},
			{
				user: 'raju',
				rating: 3,
				time: '2020-10-07T06:08:29.477Z',
				comment: 'onek valo product',
			},
			{
				user: 'raju',
				rating: 4,
				time: '2020-10-07T06:08:29.477Z',
				comment: 'onek valo product',
			},
		],
	},
	{
		id: 2,
		sku: '123abc',
		title: 'The Art of Darksiders Genesis',
		slug: 'the-art-of-darksiders-genesis',
		price: 11.99,
		discount: 10,
		image: '/images/products/book.jpg',
		category: 'Bag',
		description: {
			header:
				'Product details of PLEXTONE G20 Magnetic Stereo Bass GamingHeadphone for Mobile and Computer',
			features: [
				'Sensitivity (1Hz): - 45',
				'Microphone Directivity: Full Point',
				'Frequency response: 50-10000 Hz',
				'Signal to noise ratio: 55dB',
				'Headset:',
				'Frequency response: 20-22000 Hz',
				'Impedance: 32ohm + 15%',
				'Microphone sensitivity (1Hz): 102dB (max 1KHz)',
				'Input power: up to 5 horses',
				'Drive unit: 10mm, neodymium magnet',
			],
			specifications: [
				'Sensitivity (1Hz): - 45',
				'Microphone Directivity: Full Point',
				'Frequency response: 50-10000 Hz',
				'Signal to noise ratio: 55dB',
				'Headset:',
				'Frequency response: 20-22000 Hz',
				'Impedance: 32ohm + 15%',
				'Microphone sensitivity (1Hz): 102dB (max 1KHz)',
				'Input power: up to 5 horses',
				'Drive unit: 10mm, neodymium magnet',
			],
		},
		questionAns: [
			{
				user: 'raju',
				q: 'eta ki red color hobe?',
				a: 'sorry. eta just ekta color e ase.',
				qtime: '2020-10-07T06:08:29.477Z',
				atime: '2020-10-07T06:08:29.477Z',
			},
			{
				user: 'raju',
				q: 'eta ki red color hobe?',
				a: 'sorry. eta just ekta color e ase.',
				qtime: '2020-10-07T06:08:29.477Z',
				atime: '2020-10-07T06:08:29.477Z',
			},
			{
				user: 'raju',
				q: 'eta ki red color hobe?',
				a: 'sorry. eta just ekta color e ase.',
				qtime: '2020-10-07T06:08:29.477Z',
				atime: '2020-10-07T06:08:29.477Z',
			},
		],
		reviews: [],
	},
	{
		id: 3,
		title:
			'PDP 048-082-NA-RD Wired Controller for Xbox One, Xbox One X and Xbox One S, Crimson Red',
		slug:
			'pdp-048-082-na-rd-wired-controller-for-xbox-one-xbox-one-x-and-xbox-one-s-crimson-red',
		price: 30.2,
		rating: 3,
		discount: 10,
		image: '/images/products/joystick.jpg',
		category: 'Bag',
		description: {
			header:
				'Product details of PLEXTONE G20 Magnetic Stereo Bass GamingHeadphone for Mobile and Computer',
			features: [
				'Sensitivity (1Hz): - 45',
				'Microphone Directivity: Full Point',
				'Frequency response: 50-10000 Hz',
				'Signal to noise ratio: 55dB',
				'Headset:',
				'Frequency response: 20-22000 Hz',
				'Impedance: 32ohm + 15%',
				'Microphone sensitivity (1Hz): 102dB (max 1KHz)',
				'Input power: up to 5 horses',
				'Drive unit: 10mm, neodymium magnet',
			],
			specifications: [
				'Sensitivity (1Hz): - 45',
				'Microphone Directivity: Full Point',
				'Frequency response: 50-10000 Hz',
				'Signal to noise ratio: 55dB',
				'Headset:',
				'Frequency response: 20-22000 Hz',
				'Impedance: 32ohm + 15%',
				'Microphone sensitivity (1Hz): 102dB (max 1KHz)',
				'Input power: up to 5 horses',
				'Drive unit: 10mm, neodymium magnet',
			],
		},
		questionAns: [
			{
				q: 'eta ki red color hobe?',
				a: 'sorry. eta just ekta color e ase.',
			},
			{
				q: 'eta ki red color hobe?',
				a: 'sorry. eta just ekta color e ase.',
			},
			{
				q: 'eta ki red color hobe?',
				a: 'sorry. eta just ekta color e ase.',
			},
		],
		reviews: [
			{
				user: 'raju',
				rating: 2,
				comment: 'onek valo product',
			},
			{
				user: 'raju',
				rating: 2,
				comment: 'onek valo product',
			},
			{
				user: 'raju',
				rating: 3,
				comment: 'onek valo product',
			},
			{
				user: 'raju',
				rating: 4,
				comment: 'onek valo product',
			},
		],
	},
	{
		id: 4,
		title: 'Oculus Quest All-in-one VR Gaming Headset – 64GB',
		slug: 'oculus-quest-all-in-one-vr-gaming-headset-64gb',
		price: 249.99,
		rating: 4,
		discount: 10,
		image: '/images/products/VRkit.jpg',
		category: 'Bag',
		description: {
			header:
				'Product details of PLEXTONE G20 Magnetic Stereo Bass GamingHeadphone for Mobile and Computer',
			features: [
				'Sensitivity (1Hz): - 45',
				'Microphone Directivity: Full Point',
				'Frequency response: 50-10000 Hz',
				'Signal to noise ratio: 55dB',
				'Headset:',
				'Frequency response: 20-22000 Hz',
				'Impedance: 32ohm + 15%',
				'Microphone sensitivity (1Hz): 102dB (max 1KHz)',
				'Input power: up to 5 horses',
				'Drive unit: 10mm, neodymium magnet',
			],
			specifications: [
				'Sensitivity (1Hz): - 45',
				'Microphone Directivity: Full Point',
				'Frequency response: 50-10000 Hz',
				'Signal to noise ratio: 55dB',
				'Headset:',
				'Frequency response: 20-22000 Hz',
				'Impedance: 32ohm + 15%',
				'Microphone sensitivity (1Hz): 102dB (max 1KHz)',
				'Input power: up to 5 horses',
				'Drive unit: 10mm, neodymium magnet',
			],
		},
		questionAns: [
			{
				q: 'eta ki red color hobe?',
				a: 'sorry. eta just ekta color e ase.',
			},
			{
				q: 'eta ki red color hobe?',
				a: 'sorry. eta just ekta color e ase.',
			},
			{
				q: 'eta ki red color hobe?',
				a: 'sorry. eta just ekta color e ase.',
			},
		],
		reviews: [
			{
				user: 'raju',
				rating: 5,
				comment: 'onek valo product',
			},
			{
				user: 'raju',
				rating: 5,
				comment: 'onek valo product',
			},
			{
				user: 'raju',
				rating: 5,
				comment: 'onek valo product',
			},
			{
				user: 'raju',
				rating: 5,
				comment: 'onek valo product',
			},
		],
	},
	{
		id: 5,
		title:
			'ASUS VivoBook 15 Thin and Light Laptop, 15.6” FHD Display, Intel i3-1005G1 CPU, 8GB RAM, 128GB SSD, Backlit Keyboard, Fingerprint, Windows 10 Home in S Mode, Slate Gray, F512JA-AS34',
		slug:
			'asus-vivobook-15-thin-and-light-laptop-15.6"-fhd-display-intel-i3-1005g1-cpu-8gb-ram-128gb-ssd-backlit-keyboard-fingerprint-windows-10-home-in-s-mode-slate-gray-f512ja-as34',
		price: 549.99,
		rating: 5,
		discount: 10,
		image: '/images/products/laptop.jpg',
		category: 'Bag',
		description: {
			header:
				'Product details of PLEXTONE G20 Magnetic Stereo Bass GamingHeadphone for Mobile and Computer',
			features: [
				'Sensitivity (1Hz): - 45',
				'Microphone Directivity: Full Point',
				'Frequency response: 50-10000 Hz',
				'Signal to noise ratio: 55dB',
				'Headset:',
				'Frequency response: 20-22000 Hz',
				'Impedance: 32ohm + 15%',
				'Microphone sensitivity (1Hz): 102dB (max 1KHz)',
				'Input power: up to 5 horses',
				'Drive unit: 10mm, neodymium magnet',
			],
			specifications: [
				'Sensitivity (1Hz): - 45',
				'Microphone Directivity: Full Point',
				'Frequency response: 50-10000 Hz',
				'Signal to noise ratio: 55dB',
				'Headset:',
				'Frequency response: 20-22000 Hz',
				'Impedance: 32ohm + 15%',
				'Microphone sensitivity (1Hz): 102dB (max 1KHz)',
				'Input power: up to 5 horses',
				'Drive unit: 10mm, neodymium magnet',
			],
		},
		questionAns: [
			{
				q: 'eta ki red color hobe?',
				a: 'sorry. eta just ekta color e ase.',
			},
			{
				q: 'eta ki red color hobe?',
				a: 'sorry. eta just ekta color e ase.',
			},
			{
				q: 'eta ki red color hobe?',
				a: 'sorry. eta just ekta color e ase.',
			},
		],
		reviews: [
			{
				user: 'raju',
				rating: 5,
				comment: 'onek valo product',
			},
			{
				user: 'raju',
				rating: 5,
				comment: 'onek valo product',
			},
			{
				user: 'raju',
				rating: 5,
				comment: 'onek valo product',
			},
			{
				user: 'raju',
				rating: 5,
				comment: 'onek valo product',
			},
		],
	},
	{
		id: 6,
		title: "Samsung LC49RG90SSUXEN 49' Curved LED Gaming Monitor",
		slug: "samsung-lc49rg90ssuxen-49'-curved-led-gaming-monitor",
		price: 199.99,
		rating: 3,
		discount: 10,
		image:
			'https://images-na.ssl-images-amazon.com/images/I/71Swqqe7XAL._AC_SX466_.jpg',
		category: 'Bag',
		description: {
			header:
				'Product details of PLEXTONE G20 Magnetic Stereo Bass GamingHeadphone for Mobile and Computer',
			features: [
				'Sensitivity (1Hz): - 45',
				'Microphone Directivity: Full Point',
				'Frequency response: 50-10000 Hz',
				'Signal to noise ratio: 55dB',
				'Headset:',
				'Frequency response: 20-22000 Hz',
				'Impedance: 32ohm + 15%',
				'Microphone sensitivity (1Hz): 102dB (max 1KHz)',
				'Input power: up to 5 horses',
				'Drive unit: 10mm, neodymium magnet',
			],
			specifications: [
				'Sensitivity (1Hz): - 45',
				'Microphone Directivity: Full Point',
				'Frequency response: 50-10000 Hz',
				'Signal to noise ratio: 55dB',
				'Headset:',
				'Frequency response: 20-22000 Hz',
				'Impedance: 32ohm + 15%',
				'Microphone sensitivity (1Hz): 102dB (max 1KHz)',
				'Input power: up to 5 horses',
				'Drive unit: 10mm, neodymium magnet',
			],
		},
		questionAns: [
			{
				q: 'eta ki red color hobe?',
				a: 'sorry. eta just ekta color e ase.',
			},
			{
				q: 'eta ki red color hobe?',
				a: 'sorry. eta just ekta color e ase.',
			},
			{
				q: 'eta ki red color hobe?',
				a: 'sorry. eta just ekta color e ase.',
			},
		],
		reviews: [
			{
				user: 'raju',
				rating: 5,
				comment: 'onek valo product',
			},
			{
				user: 'raju',
				rating: 5,
				comment: 'onek valo product',
			},
			{
				user: 'raju',
				rating: 5,
				comment: 'onek valo product',
			},
			{
				user: 'raju',
				rating: 5,
				comment: 'onek valo product',
			},
		],
	},
];
