export const CUSTOMERS = [
	{
		name: 'raju',
		email: 'iqbalhossainraju47@gmail.com',
		mobile: '01853355578',
		image: '',
		address: 'sonagazi, feni.',
		country: 'bangladesh',
		district: 'feni',
		thana: 'sonagazi',
		region: 'mangalkandi',
		postal_code: '',
		home_location: '',
		timestamp: '',
	},
	{
		name: 'tushar',
		email: 'tushar@gmail.com',
		mobile: '01853565578',
		image: '',
		address: 'jatrabari, dhaka.',
		country: 'bangladesh',
		district: 'feni',
		thana: 'sonagazi',
		region: 'mangalkandi',
		postal_code: '',
		home_location: '',
		timestamp: '',
	},
	{
		name: 'asif',
		email: 'asif@gmail.com',
		mobile: '0181164648',
		image: '',
		address: 'doudkandi, comilla.',
		country: 'bangladesh',
		district: 'feni',
		thana: 'sonagazi',
		region: 'mangalkandi',
		postal_code: '',
		home_location: '',
		timestamp: '',
	},
];
