export const FETCH_PRODUCT_DETAILS = 'FETCH_PRODUCT_DETAILS';
export const ADD_PRODUCT_DETAILS = 'ADD_PRODUCT_DETAILS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const UPDATE_DELIVERY_COST = 'UPDATE_DELIVERY_COST';
