/**
 * products
 */
export const SET_CURRENT_SLUG = 'SET_CURRENT_SLUG';
export const ADD_HOME_PRODUCTS = 'ADD_HOME_PRODUCTS';
export const ADD_SEARCH_PRODUCTS = 'ADD_SEARCH_PRODUCTS';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ADD_PRODUCT_DETAILS = 'ADD_PRODUCT_DETAILS';
export const DELETE_PRODUCT_DETAILS = 'DELETE_PRODUCT_DETAILS';
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const SET_QUESTION_POSTED = 'SET_QUESTION_POSTED';
export const CLEAR_QUESTION_POSTED = 'CLEAR_QUESTION_POSTED';
export const FILTER_SEARCH_PRODUCTS = 'FILTER_SEARCH_PRODUCTS';
export const SORT_SEARCH_PRODUCTS = 'SORT_SEARCH_PRODUCTS';
export const SET_CURRENT_SEARCHED = 'SET_CURRENT_SEARCHED';

/**
 * cart
 */
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const UPDATE_DELIVERY_COST = 'UPDATE_DELIVERY_COST';
export const INITIALIZE_CART = 'INITIALIZE_CART';

/**
 * wishlist
 */
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';

/**
 * order
 */
export const ADD_ORDER = 'ADD_ORDER';
export const ADD_SELECTED_ORDER = 'ADD_SELECTED_ORDER';
export const ADD_ALL_ORDERS = 'ADD_ALL_ORDERS';
export const ADD_SINGLE_PRODUCT = 'ADD_SINGLE_PRODUCT';
export const REMOVE_SINGLE_PRODUCT = 'REMOVE_SINGLE_PRODUCT';
export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';
export const REMOVE_ORDERS = 'REMOVE_ORDERS';
export const SET_REVIEW_POSTED = 'SET_REVIEW_POSTED';
export const CLEAR_REVIEW_POSTED = 'CLEAR_REVIEW_POSTED';
export const UPDATE_GIVEN_REVIEW = 'UPDATE_GIVEN_REVIEW';

/**
 * profile information
 */

export const ADD_PROFILE = 'ADD_PROFILE';
export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';
export const SET_LOAD = 'SET_LOAD';
export const REMOVE_PROFILE = 'REMOVE_PROFILE'

/**
 * Login
 */
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

/**
 * Log out
 */
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_SUCCESS_REMEMBER = 'LOGOUT_SUCCESS_REMEMBER';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

/**
 * register
 */
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_CLEAR = 'REGISTER_CLEAR';